server:
  port: 8081

spring:
  application:
    name: ProductService
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 30
      properties:
        retry.backoff.ms: 1000
        # delivery.timeout.ms: 60000 # best practice (instead of retires and backoff)
