server:
  port: 0

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sam
    password: sam
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# spring:
#   kafka:
#     bootstrap-servers: localhost:9092,localhost:9094
#     consumer:
#       group-id: product-created-events
#       key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#       value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#       properties:
#         spring.json.trusted.packages: 'com.samic.events'
#         spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
#         spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

kafka:
  bootstrap-servers: localhost:9092,localhost:9094
  consumer:
    group-id: product-created-events
    trusted-packages: com.samic.events